# Generated by Django 4.2.7 on 2023-11-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="CPI",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="CSE_205",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="CSO_204",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="CSO_211",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="DOS",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="MA_202",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="record",
            name="ME_102",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
